 ## Numpy
 
 NumPy est une bibliothèque essentielle pour le Machine Learning, car elle permet de manipuler des tableaux (arrays) efficacement.

## 🔹 1. Installation et Importation

- pip install numpy
- import numpy as np

## 🔹 2. Création de Tableaux NumPy

Contrairement aux listes Python, les tableaux NumPy sont plus rapides et optimisés.

#### 🟢 1D : Tableau Simple

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


#### 🟢 2D : Matrice

In [3]:
matrice = np.array([[1, 2, 3], [4, 5, 6]])
print(matrice)

[[1 2 3]
 [4 5 6]]


### 🟢 Zéros, Uns, Nombres Aléatoires

In [4]:
np.zeros((3, 3))  # Matrice 3x3 de zéros
np.ones((2, 4))  # Matrice 2x4 de uns
np.random.rand(3, 3)  # Matrice 3x3 avec des valeurs aléatoires

array([[0.42353465, 0.37915728, 0.20330777],
       [0.75162235, 0.97963422, 0.29958879],
       [0.6540601 , 0.66324388, 0.03902091]])

## 🔹 3. Manipulation des Tableaux

### 🟢 Accéder aux éléments

In [5]:
arr = np.array([10, 20, 30, 40])
print(arr[1])  # 20
print(arr[-1])  # 40

20
40


### 🟢 Slicing (Extraction de sous-tableaux)

In [6]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])  # [20 30 40]

[20 30 40]


### 🟢 Modifier un élément

In [7]:
arr[2] = 99  # Change 30 en 99
print(arr)  # [10 20 99 40 50]

[10 20 99 40 50]


## 🔹 4. Opérations Mathématiques

NumPy permet de faire des opérations vectorielles ultra-rapides.

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  # [5 7 9]
print(a * b)  # [4 10 18]
print(a ** 2)  # [1 4 9]
print(np.sqrt(a))  # Racine carrée

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]


💡 **Exercice**  
1️⃣ Crée une **matrice 3x3** avec des nombres de **1 à 9**.  
2️⃣ Affiche **l’élément au centre** de la matrice.  
3️⃣ Multiplie la **matrice par 2** et affiche le résultat.  

In [9]:
# 1️⃣ Création de la matrice 3x3
matrice = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])

# 2️⃣ Affichage de l’élément central
print("Élément central :", matrice[1, 1])

# 3️⃣ Multiplication de la matrice par 2
matrice_x2 = matrice * 2
print("Matrice multipliée par 2 :\n", matrice_x2)

Élément central : 5
Matrice multipliée par 2 :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


🚀 **Concepts clés :**  
✅ Une **matrice** est une structure en **2 dimensions** (tableau 2D).  
✅ `matrice[1, 1]` permet d’**accéder à l’élément central** (indice **1,1**).  
✅ `matrice * 2` **multiplie chaque élément** de la matrice par **2**.  

# 🚀 Exercices Python : Manipulation des Structures de Données

## 🔹 Exercice 1 : Manipulation des Listes
1️⃣ Crée une liste contenant les nombres de 1 à 10.  
2️⃣ Affiche le troisième élément de la liste.  
3️⃣ Ajoute le nombre 11 à la fin de la liste.  
4️⃣ Supprime le premier élément de la liste.  
5️⃣ Affiche la liste mise à jour.  

---

## 🔹 Exercice 2 : Manipulation des Tuples
1️⃣ Crée un tuple contenant trois chaînes de caractères.  
2️⃣ Décompose ce tuple en trois variables et affiche-les.  
3️⃣ Essaye de modifier un élément du tuple. Que se passe-t-il ?  

---

## 🔹 Exercice 3 : Opérations sur une Matrice (NumPy)
1️⃣ Crée une matrice 3x3 contenant les nombres de 1 à 9.  
2️⃣ Affiche l’élément situé au centre de la matrice.  
3️⃣ Multiplie tous les éléments de la matrice par 2 et affiche le résultat.  
4️⃣ Affiche la diagonale principale de la matrice.  

---

## 🔹 Exercice 4 : Dictionnaires en Python
1️⃣ Crée un dictionnaire contenant les informations suivantes :
   - `nom`: Alice
   - `âge`: 25
   - `ville`: Paris  
2️⃣ Affiche la valeur associée à la clé `nom`.  
3️⃣ Ajoute une nouvelle clé `profession` avec la valeur `"Ingénieure"`.  
4️⃣ Modifie la valeur associée à la clé `ville` pour `"Lyon"`.  
5️⃣ Supprime la clé `âge` du dictionnaire.  
6️⃣ Affiche le dictionnaire mis à jour.  

---

## 🔹 Exercice 5 : Boucles et Conditions
### 🔸 Partie 1
1️⃣ Écris une boucle qui affiche les nombres de 1 à 10.  
2️⃣ Remplace chaque multiple de 3 par `"Fizz"`.  

### 🔸 Partie 2
1️⃣ Écris une fonction `pair_ou_impair(n)` qui prend un nombre en entrée et retourne `"Pair"` s'il est pair et `"Impair"` sinon.  
2️⃣ Teste la fonction avec différents nombres.  

---

## 🎯 Bonus : Exercices Avancés
### 🔸 Exercice 6 : Manipulation des Chaînes de Caractères
1️⃣ Demande à l'utilisateur de saisir une phrase.  
2️⃣ Convertis la phrase en minuscules et remplace les espaces par des tirets `-`.  
3️⃣ Affiche le nombre total de caractères dans la phrase (sans les espaces).  

### 🔸 Exercice 7 : Génération de Nombres Aléatoires
1️⃣ Génère une liste de 10 nombres aléatoires entre 1 et 100.  
2️⃣ Trouve et affiche le nombre le plus grand et le plus petit de la liste.  
3️⃣ Trie la liste par ordre croissant.  

---

🔥 **Prêt à relever le défi ? Bonne chance !** 😃💪


### 🚀 Solutions des Exercices Python : Manipulation des Structures de Données

### ✅ Exercice 1 : Manipulation des Liste

In [11]:
# Création de la liste
ma_liste = list(range(1, 11))

# Affichage du troisième élément
print("Troisième élément :", ma_liste[2])

# Ajout du nombre 11
ma_liste.append(11)

# Suppression du premier élément
ma_liste.pop(0)

# Affichage de la liste mise à jour
print("Liste mise à jour :", ma_liste)


Troisième élément : 3
Liste mise à jour : [2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


✅ Explication :
- list(range(1, 11)) génère une liste de 1 à 10.
- ma_liste[2] permet d'accéder au troisième élément.
- .append(11) ajoute 11 à la fin de la liste.
- .pop(0) supprime le premier élément.
- La liste finale est affichée.

### ✅ Exercice 2 : Manipulation des Tuples

In [12]:
# Création du tuple
mon_tuple = ("Python", "Java", "C++")

# Décomposition
a, b, c = mon_tuple
print("Langages :", a, b, c)

# Essai de modification
# mon_tuple[0] = "JavaScript"  # Erreur !


Langages : Python Java C++


✅ Explication :
- Les tuples sont immuables (on ne peut pas modifier leurs éléments après leur création).
- Une affectation a, b, c = mon_tuple permet de décomposer le tuple.

### ✅ Exercice 3 : Opérations sur une Matrice (NumPy)

In [13]:
# Création de la matrice 3x3
matrice = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Affichage de l'élément central
print("Élément central :", matrice[1, 1])

# Multiplication par 2
matrice_double = matrice * 2
print("Matrice multipliée par 2 :\n", matrice_double)

# Affichage de la diagonale
print("Diagonale principale :", np.diag(matrice))


Élément central : 5
Matrice multipliée par 2 :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Diagonale principale : [1 5 9]


✅ Explication :
- np.array() crée une matrice NumPy.
- matrice[1, 1] accède à l'élément du centre (indice 1,1).
- matrice * 2 multiplie chaque élément par 2.
- np.diag(matrice) extrait la diagonale principale.

### ✅ Exercice 4 : Dictionnaires en Python

In [14]:
# Création du dictionnaire
personne = {"nom": "Alice", "âge": 25, "ville": "Paris"}

# Affichage du nom
print("Nom :", personne["nom"])

# Ajout de la profession
personne["profession"] = "Ingénieure"

# Modification de la ville
personne["ville"] = "Lyon"

# Suppression de l'âge
del personne["âge"]

# Affichage du dictionnaire final
print("Dictionnaire mis à jour :", personne)


Nom : Alice
Dictionnaire mis à jour : {'nom': 'Alice', 'ville': 'Lyon', 'profession': 'Ingénieure'}


✅ Explication :
- **{}** définit un dictionnaire.
- personne["nom"] permet d'accéder à une valeur.
- personne["clé"] = valeur permet d'ajouter/modifier une clé.
- **del** personne["âge"] supprime une clé.

### ✅ Exercice 5 : Boucles et Conditions

In [15]:
# Affichage des nombres avec "Fizz"
for i in range(1, 11):
    if i % 3 == 0:
        print("Fizz")
    else:
        print(i)

# Fonction pair ou impair
def pair_ou_impair(n):
    return "Pair" if n % 2 == 0 else "Impair"

# Test de la fonction
print(pair_ou_impair(4))  # Pair
print(pair_ou_impair(7))  # Impair


1
2
Fizz
4
5
Fizz
7
8
Fizz
10
Pair
Impair


✅ Explication :
- if i % 3 == 0 remplace les multiples de 3 par "Fizz".
- return "Pair" if n % 2 == 0 else "Impair" est une condition ternaire.

### ✅ Exercice 6 : Manipulation des Chaînes de Caractères

In [16]:
# Entrée utilisateur
phrase = input("Entrez une phrase : ")

# Mise en minuscules et remplacement des espaces
modifiee = phrase.lower().replace(" ", "-")

# Nombre de caractères sans espaces
nb_caracteres = len(phrase.replace(" ", ""))

print("Phrase modifiée :", modifiee)
print("Nombre de caractères (sans espaces) :", nb_caracteres)


Phrase modifiée : mamadou-va-à-l'école
Nombre de caractères (sans espaces) : 17


✅ Explication :
- lower() convertit en minuscules.
- replace(" ", "-") remplace les espaces par -
- len(phrase.replace(" ", "")) compte les caractères sans espaces.

### ✅ Exercice 7 : Génération de Nombres Aléatoires

In [17]:
import random

# Génération de 10 nombres aléatoires
nombres = [random.randint(1, 100) for _ in range(10)]

# Affichage du min et max
print("Liste :", nombres)
print("Plus grand :", max(nombres))
print("Plus petit :", min(nombres))

# Tri de la liste
nombres.sort()
print("Liste triée :", nombres)


Liste : [28, 48, 87, 72, 78, 77, 95, 23, 74, 86]
Plus grand : 95
Plus petit : 23
Liste triée : [23, 28, 48, 72, 74, 77, 78, 86, 87, 95]


✅ Explication :
- random.randint(1, 100) génère un nombre aléatoire
- max() et min() trouvent les extrêmes
- sort() trie la liste